---
- name: Create users on server
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    groups: [sudo]
    append: true
    state: present
    create_home: true
    password: "{{ item.password | password_hash('sha512') }}"
    update_password: on_create
  register: user

- name: Add ssh user keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"

- name: force change password
  command: "chage -d 0 {{ item.name }}"
  when: user.changed